---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-9883c6f2
      tags:
        Name: test-kitchen-et-mesos-ubuntu-1404
        Env: testing
  - name: centos-6.6
    driver_config:
      image_id: UNDECIDED

suites:
  - name: mesosphere_master
    run_list:
      - recipe[et_mesos::master]
    attributes:
      et_mesos:
        type: mesosphere
        mesosphere:
          with_zookeeper: true
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        agent_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6

  - name: mesosphere_agent
    run_list:
      # master recipe is only for asserting mesos-agent healthy startup.
      - recipe[et_mesos::master]
      - recipe[et_mesos::agent]
    attributes:
      et_mesos:
        type: mesosphere
        agent:
          attributes:
            rackid: us-east-1b
          master: 'zk://localhost:2181/mesos'
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        # these keys below are only for master configurations.
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        agent_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6
        mesosphere:
          with_zookeeper: true

  - name: source_master
    run_list:
      - recipe[et_mesos::master]
    attributes:
      et_mesos:
        type: source
        master:
          zk: 'zk://localhost:2181/mesos'
          quorum: 1
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        agent_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6

  - name: source_agent
    run_list:
      # master recipe is only for asserting mesos-agent healthy startup.
      - recipe[et_mesos::master]
      - recipe[et_mesos::agent]
    attributes:
      et_mesos:
        type: source
        master:
          zk: 'zk://localhost:2181/mesos'
          ip: 127.0.0.1
          quorum: 1
        agent:
          attributes:
            rackid: us-east-1b
          master: 127.0.0.1:5050
        # these keys below are only for master configurations.
        master_ips:
          - 10.0.0.1
          - 10.0.0.2
          - 10.0.0.3
        agent_ips:
          - 10.0.0.4
          - 10.0.0.5
          - 10.0.0.6
